# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('technology', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('select', 'Select'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='select', max_length=20, verbose_name='Application Status')),
            ],
        ),
    ]
